Add uniswap v3 support
tradingstrategy-ai/trade-executor pull request #153
Opened 2022-12-23 15:15 UTC by AlexTheLion123

Related to #140

2022-12-23 15:15 UTC, AlexTheLion123 commented
Fixes #142

2022-12-23 15:16 UTC, AlexTheLion123 commented
TODO: discard `pyproject.toml` changes

2023-01-26 09:44 UTC, miohtama requested changes

2023-01-26 09:44 UTC, miohtama commented on tradeexecutor/strategy/default_routing_options.py
> +    uniswap_v3_busd = "uniswap_v3_busd"
There are no significant BUSD pairs on any Uniswap v3 exchanges

2023-01-26 09:44 UTC, miohtama commented on tradeexecutor/ethereum/uniswap_v3_execution.py
> +class UniswapV3ExecutionModel(ExecutionModel):
We can get away with the same execution model  for Uniswap v2 and v3, so it is unlikely we need to have a new class.

This code needs to be rethought,

2023-01-26 09:44 UTC, miohtama commented on tradeexecutor/ethereum/execution_uniswap_v3.py
> +import logging
There is no need to create a separate execution module for Uniswap v3, because this is mostly copy-paste from the existing execution module.

2023-01-26 09:44 UTC, miohtama commented on tradeexecutor/ethereum/constants.py
> +"""Defines constants for routing, especially fee data for different exchanges"""
These are no longer needed, as this has been fixed in the backend  and fees are part of DEXPair dataset.

2023-03-16 10:49 UTC, closed without merging