Uniswap V3 Backtesting
tradingstrategy-ai/trade-executor pull request #187
Opened 2023-01-31 06:59 UTC by AlexTheLion123

Adds support for uniswap V3 backtesting. 

This is done by ...

2023-01-31 07:10 UTC, AlexTheLion123 commented
fixes #140, fixes #188

2023-01-31 15:54 UTC, miohtama requested changes

2023-01-31 15:54 UTC, miohtama commented on tradeexecutor/ethereum/uniswap_v3_routing.py
> +class OutOfBalance(Exception):
Use same exception for Uniswap v2 and v3

2023-01-31 15:54 UTC, miohtama commented on tradeexecutor/ethereum/uniswap_v3_routing.py
> +class UniswapV3RoutingState(RoutingState):
Use same base class for v2 and v3 routing, so that we do not copy paste any code

2023-02-01 17:18 UTC, AlexTheLion123 commented
@miohtama Have created `RoutingState` base class in `routing_state.py`

2023-02-02 09:33 UTC, miohtama requested changes

2023-02-02 10:46 UTC, AlexTheLion123 commented on tradeexecutor/ethereum/uniswap_v2_routing.py
> +class UniswapV2RoutingState(RoutingStateBase):
@miohtama It isn't the same, there is `UniswapV3RoutingState(RoutingStateBase)` as well. 
https://github.com/tradingstrategy-ai/trade-executor/blob/52e38e009110c53f184dabea115f7d146e1725c2/tradeexecutor/ethereum/uniswap_v3_routing.py#L34-L117

2023-02-02 10:46 UTC, AlexTheLion123 commented on tradeexecutor/ethereum/uniswap_v2_routing.py
> +class UniswapV2RoutingState(RoutingStateBase):
@miohtama It isn't the same, there is `UniswapV3RoutingState(RoutingStateBase)` as well. 
https://github.com/tradingstrategy-ai/trade-executor/blob/52e38e009110c53f184dabea115f7d146e1725c2/tradeexecutor/ethereum/uniswap_v3_routing.py#L34-L117

2023-02-02 10:47 UTC, AlexTheLion123 commented on tradeexecutor/ethereum/uniswap_v3_routing.py
> +class UniswapV3SimpleRoutingModel(RoutingModel):
Will add a base class for the routing model as well.

2023-02-02 15:02 UTC, miohtama requested changes
- Still need a test case that uses the new Uni v3 classes

2023-02-03 08:56 UTC, merged