Detached indicator
tradingstrategy-ai/trade-executor pull request #267
Opened 2023-03-31 00:08 UTC by AlexTheLion123

- adds support for detached indicator plots
- Also adds various user options to customize subplots. These include:
      1. Subplot color
      2. Horizontal line through subplot
      3. Relative sizing (detached only)
      4. Vertical spacing (detached only)
- Adds example of detached indicators in notebook
    
![detached_indicators](https://user-images.githubusercontent.com/74208897/228991105-42c20b84-753c-4610-96d8-06cee8f32cec.png)

2023-03-31 11:24 UTC, miohtama requested changes

2023-03-31 11:24 UTC, miohtama commented on tradeexecutor/visual/technical_indicator.py
> +    if line_val := plot.horizontal_line:
It's a bad practice to do conditional functions.

It is better to check this at the call site and then only call the function if the conditions are sufficient

2023-03-31 11:24 UTC, miohtama commented on tradeexecutor/visual/technical_indicator.py
> +def _get_start_and_end(start_at, end_at, plot):
Need type decorations in the arguments

2023-03-31 11:24 UTC, miohtama commented on tradeexecutor/visual/technical_indicator.py
> +def _add_hline(fig, start_at, end_at, cur_row, plot: Plot):
Need type decorations in the arguments

2023-04-05 15:40 UTC, AlexTheLion123 commented
Closing and including code inside #271

2023-04-05 15:40 UTC, closed without merging