Detached indicator overlay
tradingstrategy-ai/trade-executor pull request #271
Opened 2023-04-03 16:05 UTC by AlexTheLion123

- add support for overlaying technical indicator on top of another already detached technical indicator

2023-04-03 16:06 UTC, AlexTheLion123 commented
TODO: remove notebook change

2023-04-06 14:07 UTC, AlexTheLion123 commented
fixes #272

2023-04-07 07:38 UTC, miohtama requested changes

2023-04-07 07:38 UTC, miohtama commented on tradeexecutor/state/visualisation.py
> +    detached_overlay_name: str | None = None
Make `Optional[]` so it is in line with other attributes in this data class

2023-04-07 08:35 UTC, merged