Support visualization & analysis for shorting
tradingstrategy-ai/trade-executor pull request #568
Opened 2023-09-18 22:10 UTC by hieuh25

2023-09-18 22:11 UTC, hieuh25 commented on tradeexecutor/visual/single_pair.py
> +        # f"Entry price: {first_trade.planned_mid_price:.2f} USD (mid price)",
@miohtama I can look closer at this tomorrow, but do you have any idea why `planned_mid_price` is None here?

2023-09-19 08:14 UTC, miohtama requested changes

2023-09-19 08:14 UTC, miohtama commented on tradeexecutor/analysis/trade_analyser.py
> +            pair_id = position.pair.underlying_spot_pair.internal_id
You can call `position.pair.get_pricing_pair()` here so you do not need `if`

2023-09-19 08:14 UTC, miohtama commented on tradeexecutor/visual/utils.py
> +        base_token_symbol = t.pair.base.underlying.token_symbol
Same as above

2023-09-19 08:14 UTC, miohtama commented on tradeexecutor/visual/utils.py
> +                if t.pair.underlying_spot_pair.internal_id != pair_id:
Same as above

2023-09-19 08:14 UTC, miohtama commented on tradeexecutor/visual/utils.py
> +        if p.is_long():
Should be if `p.is_spot()`

2023-09-19 09:24 UTC, merged